### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#1]
Currently Chitchatter uses the default Create React App logo: https://github.com/jeremyckahn/chitchatter/blob/develop/public/logo512.png

The project needs something more distinctive and unique.

**Comment by ramyashreeshetty** [comment]
can u assign me this issue?

**Comment by jeremyckahn** [comment]
Hi @ramyashreeshetty, thanks for offering to help with this! Do you have any logo mocks or design concepts you can share? I'd like to understand what you've got in mind before assigning ownership of the work.

**Comment by ramyashreeshetty** [comment]
@jeremyckahn yes! as we are looking for a favicon. So a logo would be enough. But in addition to that, we can also create a logo (text+icon) for the official project. 
![mock design](https://user-images.githubusercontent.com/43513353/189544156-c19c82e3-0fb8-46c1-a135-82bb7bc617bd.png)

let me know if you have any specific colour in ur mind. As the name of the project is chitchatter we could have a CC combination in our logo.

**Comment by jeremyckahn** [comment]
Oh wow, these look great @ramyashreeshetty! Excellent work. Of the samples provided, this is the one that I think works the best: 
![Sample screenshot](https://user-images.githubusercontent.com/366330/189544975-0b1f12a0-9514-42fa-94bb-2eb732002e49.png)

To me, this strikes the best balance between distinctiveness and scalability (It will work both as a favicon and also a native app icon).

As for colors, we will need something that sticks out against both dark and light grey backgrounds. Right now Chitchatter is using the [default Material UI theme](https://mui.com/material-ui/customization/default-theme/), so for consistency we might want to consider using colors from that palette: 
![Dark color palette screenshot](https://user-images.githubusercontent.com/366330/189545176-04e05ba7-a7fc-45c9-adfa-261150680c60.png) 
![Light color palette screenshot](https://user-images.githubusercontent.com/366330/189545270-a8f45b6d-d4f8-4245-a833-5eead7bea551.png)


That said, I'm not a designer and I don't want to be overly prescriptive with color choices. I trust your judgement to make something that works visually. 🙂

I will assign this issue to you. When you're done, please provide any source (PSD, SVG, etc.) files so we can keep those tracked in Git. Thanks for the great work so far!

**Comment by ramyashreeshetty** [comment]
hey these are a few designs I could come up with

![cc logo1](https://user-images.githubusercontent.com/43513353/189547915-e2d79daf-be93-4727-9d11-128a8d07fc9e.svg)
![cc logo2](https://user-images.githubusercontent.com/43513353/189547916-ed8925a0-5f03-4f22-bace-0d6916e960ae.svg)
![cc favicon](https://user-images.githubusercontent.com/43513353/189547917-2ad81c2c-29e0-4647-a09c-f9985dc89440.svg)

let me know if any changes are required

**Comment by jeremyckahn** [comment]
@ramyashreeshetty these are great!! Awesome work. These are the versions I'd like to use:

![Chitchatter logo with name](https://user-images.githubusercontent.com/43513353/189547916-ed8925a0-5f03-4f22-bace-0d6916e960ae.svg)

![Chitchatter logo](https://user-images.githubusercontent.com/43513353/189547917-2ad81c2c-29e0-4647-a09c-f9985dc89440.svg)

Would you be able to share the source files you used as a comment attachment? If so, I can get this integrated into the project and ship this to users. 🙂

**Comment by ramyashreeshetty** [comment]
How do you want me to share the source files should create a PR or share through some other source?

**Comment by jeremyckahn** [comment]
Sharing via Pull Request should work just fine! That way you will be included in the commit history.

**Comment by jeremyckahn** [comment]
@ramyashreeshetty the logo is now live at https://chitchatter.im/. Thanks again for the amazing work! 🙏
