### ISSUE TITLE
Request: Make chat less spaced apart by default

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#110]
Right now the chat is spread very far apart on a 1080p monitor, maybe making it a bit more constrained would be a bit better?

![Screenshot 2023-03-15 001706](https://user-images.githubusercontent.com/56714680/225205241-88fd1156-e0db-44fd-965a-81e2785509a5.png)

As you can see that's quite a bit of distance between my message and the other person's reply.

**Comment by jeremyckahn** [comment]
This is fixed in #111 and should be live [shortly](https://github.com/jeremyckahn/chitchatter/actions/runs/4427851678). @dillfrescott let me know how you like it! 🙂

**Comment by dillfrescott** [comment]
I actually really like that! Thank you so much!
