### ISSUE TITLE
QR code support

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#12]
Users should be able to request a QR code to be presented that links to the current room.

**Comment by worry** [comment]
Been using this little library to do quick QR codes in a canvas element - very easy to use: https://davidshimjs.github.io/qrcodejs/

**Comment by jeremyckahn** [comment]
This is handy! Thanks @worry!

**Comment by krayste** [comment]
This may be a dumb question @worry but how would you include this in chitchatter? Seems like it's some standalone code and not published on NPM, as well as not being actively supported - perhaps [qrcode.react](https://www.npmjs.com/package/qrcode.react) may be a suitable replacement?

**Comment by krayste** [comment]
@jeremyckahn 
Does something like this work? I'm using [`react-qrcode-logo`](https://www.npmjs.com/package/react-qrcode-logo) so that the chitchatter logo can be overlaid with some transparency. The navbar icons are also broken on mobile but addressed by moving the QRCode, copy, and peer list buttons into the drawer on mobile 👍 
![image](https://user-images.githubusercontent.com/18077772/200121719-7038ddcc-34e4-4e11-940f-cefa1edbde5a.png)

**Comment by jeremyckahn** [comment]
@krayste this mockup looks excellent! Nice work. I think it would work well with the overall UI, so please open a PR when you've got something you'd like to merge.

> The navbar icons are also broken on mobile but addressed by moving the QRCode, copy, and peer list buttons into the drawer on mobile +1

Is this to say that the navbar icons are currently broken on the `main`/`develop` branches? If so, I'd be surprised to hear that since everything seems to work well on my iPhone SE. Or were you referring to the current state of what you've got mocked up?

**Comment by krayste** [comment]
Sorry @jeremyckahn I should've been more clear when. There isn't enough space in the navbar to accommodate for all three icons on iPhone SE so it looks awkward when I tried to add another QR code icon. Will refactor to include in the drawer
![image](https://user-images.githubusercontent.com/18077772/200146197-860f41c2-63ec-4526-bb5f-5749801b1cff.png)

**Comment by krayste** [comment]
Sorryy @jeremyckahn, I should've been more clear that it was difficult to get all three icons on the navbar without cutting off the room code, but I see that's how it is in the current design. I'll leave it as such

**Comment by jeremyckahn** [comment]
Ah yes! Room names can be arbitrarily long, so I'm not too concerned about it being truncated on smaller screens. Granted, we don't want to get too carried away with what's in the navbar, but I think what you've got mocked up should be just fine. 🙂

**Comment by krayste** [comment]
Cheers @jeremyckahn, have opened a PR here https://github.com/jeremyckahn/chitchatter/pull/63
