### ISSUE TITLE
Upload file infinite loading glitch

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#122]
If you upload a file, cancel it, then open the file picker on desktop again and hit cancel, it causes the file upload button to infinitely spin and you need to refresh the page to fix it.

![Screenshot 2023-05-19 202636](https://github.com/jeremyckahn/chitchatter/assets/56714680/484831fc-b9f5-4a15-86d9-15ad9b15765c)

**Comment by jeremyckahn** [comment]
Thanks for reporting this @dillfrescott! I've noticed similar behavior as well, and it's good to have it tracked like this.

This is certainly an annoying state management issue. It seems to stem from quirky behavior from WebTorrent (via https://github.com/jeremyckahn/secure-file-transfer, which is the core of the file transfer functionality).

I won't have bandwidth to look into this in the immediate future, so I'll leave this open for anyone else to look into if they'd like to before I get a chance.

**Comment by jeremyckahn** [comment]
I'm struggling to reproduce this issue now. I performed these steps to reproduce:

> upload a file, cancel it, then open the file picker on desktop again and hit cancel

But it seems to work as expected. @dillfrescott are you able reproduce this some other way?

**Comment by dillfrescott** [comment]
![Screenshot_20230724_215529](https://github.com/jeremyckahn/chitchatter/assets/56714680/fd7dcbe3-9f8c-439f-93dd-dce7a2c3465a)

Was just able to replicate it again very easily doing the same steps as before. Very odd that its not doing it for you.

**Comment by jeremyckahn** [comment]
Yeah that's really strange. I have seen the issue you're describing, but it happens inconsistently and I can't find a way to reliably reproduce and fix it. 😕

**Comment by jeremyckahn** [comment]
I was able to reproduce the bug! It seems to only happen (consistently) in Chromium. I usually use Firefox which is why I didn't see it before.

**Comment by jeremyckahn** [comment]
@dillfrescott I've got a PR with a potential fix at #131. Would you mind giving [the preview build](https://chitchatter-git-bugfix-122stuck-file-picker-jeremyckahn.vercel.app/) a try and seeing if the issue is fixed for you?

**Comment by jeremyckahn** [comment]
I went ahead and merged #131. It's a safe change, so we might as well deploy it and see if it helps. Please let me know if this resolves the issue for you @dillfrescott!

**Comment by dillfrescott** [comment]
Sorry I couldn't get back to you sooner. I just tested it and it works great! Good job squashing that bug!
