### ISSUE TITLE
bugs & feature requests

### ISSUE THREAD

**Issue by africa552036012020255252355634346346346** [jeremyckahn/chitchatter#135]
**bugs**
when expanding the user list on phone it breaks the ui's vertical scrolling & horizontal looks off

on brave android when minimizing the browser it makes a sound but nor notifications nor messages appear in chat, not the case on firefox android

when deleting a shared image the spinning loading message thing stays there just spinning 
(make it say deleted for a few sec then remove the msg when deleting)

**feature requests to make it top notch** (a few have already been suggested)

- emoji reactions on msg's

- cursor share (easy in trystero) + live msg's

- replies to specific messages

- functionality delivering web push messages on all devices even when app is closed

- live active public room list with # of active users (integrated neatly into the room name selector)

- abillity to have persistent chats (locally + blockchain hosted) & timed autodelete

- cryptocurrency integration (with ability to easily donate to the developer(s))

- multiplayer games (with cryptocurrency integration)

- ai integration (let ai develop the suggested features here ✨)

- persistent user id's; dm's, pfp's & profiles

**Comment by jeremyckahn** [comment]
Hi @africa552036012020255252355634346346346, thanks for reporting all of this.

> when expanding the user list on phone it breaks the ui's vertical scrolling & horizontal looks off

Yeah I've noticed that too. I'd appreciate some help with addressing that if you or anyone else is interested!

> on brave android when minimizing the browser it makes a sound but nor notifications nor messages appear in chat, not the case on firefox android

Good to know, thanks for reporting.

> when deleting a shared image the spinning loading message thing stays there just spinning
(make it say deleted for a few sec then remove the msg when deleting)

Yeah there's a few state issues related to image/video sharing. I'll try to improve that when I can.

Of the feature requests you mentioned, these are the ones that I'd also like to see in Chitchatter:

> * emoji reactions on msg's
> * replies to specific messages
> * persistent user id's; dm's

Some of the other features are interesting, but it would increase Chitchatter's scope beyond what I'd like it to be.

**Comment by jeremyckahn** [comment]
Thanks for sharing the fork, @africa552036012020255252355634346346346. That's certainly a unique theme for Chitchatter! 🙂

I think it's worth fixing the UI issues you brought up. Fortunately these are mostly annoyances rather than major bugs, but I agree that it will allow for a much more polished experience once they're addressed.

I've broken out all the issues I'd like to get resolved into their own tickets, so I'm going to close this one for now. Thanks again for raising all of these!
