### ISSUE TITLE
Direct messages

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#141]
_Originally requested by @africa552036012020255252355634346346346 in https://github.com/jeremyckahn/chitchatter/issues/135#issue-1842429204_

**Comment by Agility0493** [comment]
@jeremyckahn any updates on this?

**Comment by jeremyckahn** [comment]
> any updates on this?

Not yet, but I think this feature is increasingly important given the recent release of [community rooms on the Home page](https://github.com/jeremyckahn/chitchatter/pull/372). While I'm currently focused on other projects, I'd like to explore an MVP version of this feature once I reach a stopping point.

**Comment by Agility0493** [comment]
> > any updates on this?
> 
> Not yet, but I think this feature is increasingly important given the recent release of [community rooms on the Home page](https://github.com/jeremyckahn/chitchatter/pull/372). While I'm currently focused on other projects, I'd like to explore an MVP version of this feature once I reach a stopping point.

Thank you Jeremy, love the progress here! I'll want to contribute more in the future to this project. Direct messages make this a lot more useful for daily comms.

**Comment by jeremyckahn** [comment]
Direct message functionality has been shipped and is live on https://chitchatter.im/.
