### ISSUE TITLE
3 issues I noticed

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#156]
Really been loving Chitchatter lately but I noticed 3 small issues with it:

1. On android sometimes the backfilling of images gets stuck in a loading forever state.
2. On iPhone (probably iPad too) when sending a picture, the user gets removed from the room. Not sure if you can fix that one.
3. When there are a few messages in chat on Desktop, the form factor of the chat kinda goes wonky:

![Screenshot 2023-09-05 110626](https://github.com/jeremyckahn/chitchatter/assets/56714680/d2d20599-9399-4e5f-81b4-4dd0f514294e)

as you can see there is some dead space there.

**Comment by jeremyckahn** [comment]
Hi @dillfrescott, thanks for reporting these issues! I've broken this issue out into #158, #159, and #160.

> When there are a few messages in chat on Desktop, the form factor of the chat kinda goes wonky

The width of the content is intentionally constrained so that it does not get too wide (#110). The scrollbar is indeed in an odd place, but I think that could be improved by a styling change.

**Comment by dillfrescott** [comment]
Oh okay! Thank you so much for opening the issues too!

**Comment by jeremyckahn** [comment]
> 3\. When there are a few messages in chat on Desktop, the form factor of the chat kinda goes wonky:
> 
> 
> ![Screenshot 2023-09-05 110626](https://user-images.githubusercontent.com/56714680/265743463-d2d20599-9399-4e5f-81b4-4dd0f514294e.png)
> 
> as you can see there is some dead space there.

@dillfrescott this is addressed by #212 and is [live now](https://github.com/jeremyckahn/chitchatter/actions/runs/6973255044/job/18976925266). Thanks for the suggestion!
