### ISSUE TITLE
Move transcript scrollbar to edge of container

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#160]
From @dillfrescott in #156:

> When there are a few messages in chat on Desktop, the form factor of the chat kinda goes wonky:
>
> ![Screenshot of issue](https://github.com/jeremyckahn/chitchatter/assets/366330/4e798e4a-cee1-4cae-9332-adbc5026d55f)

**Comment by dillfrescott** [comment]
Excellent! Thank you so much!
