### ISSUE TITLE
Indicate Markdown support

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#17]
It should be clearly indicated to the user that they can use Markdown in their messages.

**Comment by jeremyckahn** [comment]
This should be easy enough to implement, but I'm not sure what design would work here. I don't want to clutter up the chat UI, especially on mobile.

![Chat room screenshot](https://user-images.githubusercontent.com/366330/190433015-1820a983-371e-41ee-8f2c-d20574c69727.png)

**Comment by jeremyckahn** [comment]
This seems like a good reason to set up an "about" screen to display information about the app to the user.

**Comment by MohammadTaseenKhan** [comment]
How about having a glowing effect like this



![Image](https://user-images.githubusercontent.com/85288261/193466071-f3cfe804-eb9f-4792-ab5c-35f0627e6bc4.png)


During typing it will look like this 



![Image](https://user-images.githubusercontent.com/85288261/193466099-f1cb9305-008f-41ed-9ad4-d7cc7efe1195.png)

**Comment by MohammadTaseenKhan** [comment]
![Image](https://user-images.githubusercontent.com/85288261/193466290-295974c3-b629-4a4c-939d-53b28d20014d.png)

**Comment by jeremyckahn** [comment]
@MohammadTaseenKhan What's the motivation for making this change?

**Comment by MohammadTaseenKhan** [comment]
@jeremyckahn My friends and colleagues liked this design very much

**Comment by MohammadTaseenKhan** [comment]
so I thought about sharing it to you                       Although your design is also different from other services like Tox 



![Image](https://user-images.githubusercontent.com/85288261/193496091-77841849-0c76-4c63-a452-dfdbec8864c6.png)

**Comment by jeremyckahn** [comment]
@MohammadTaseenKhan got it. What you've shown is a cool design, but personally I prefer the current one. I think it's worth keeping Chitchatter simple and "boring" looking so that it is approachable by the most amount of people. I'm open to changing the UI, but I'd like to design with accessibility in mind.

If you'd like to discuss UI changes further, please [start a discussion thread](https://github.com/jeremyckahn/chitchatter/discussions/new) and we can take it from there!
