### ISSUE TITLE
Limit the size of messages

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#18]
Chat messages should be limited to 10,000 characters.

**Comment by jeremyckahn** [comment]
Hi @ighmaZ, I think the solution for this ticket will require a change in https://github.com/jeremyckahn/chitchatter/blob/develop/src/components/MessageForm/MessageForm.tsx. Is this something you'd like to work on?

**Comment by ighmaZ** [comment]
@jeremyckahn okay ill take this issue

**Comment by jeremyckahn** [comment]
It's been assigned to you. Thank you @ighmaZ! Let me if you need any help.
