### ISSUE TITLE
Starting a screenshare with sound should have the screenshare muted for the person who is sharing the screen

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#180]
Because right now I have to click show controls and mute it or else I get some feedback from my own screenshare.

**Comment by jeremyckahn** [comment]
Good idea! I'll add this to the backlog.

**Comment by dillfrescott** [comment]
I was thinking that when you add this maybe you can add a volume slider for the screenshare audio. Right now you can do a workaround by right clicking and clicking on `show controls` but having a dedicated bar would be very nice!

**Comment by jeremyckahn** [comment]
@dillfrescott That's a great idea. I can look into that sometime after I complete the current feature focus (#183)!

**Comment by dillfrescott** [comment]
Sounds good!

**Comment by jeremyckahn** [comment]
@dillfrescott thank you so much for sponsoring me on GitHub! I'm planning to make this my next Chitchatter development task. 🙂

**Comment by dillfrescott** [comment]
Cool! Take your time! And thanks!

**Comment by jeremyckahn** [comment]
This was fixed in #200 and is [deploying now](https://github.com/jeremyckahn/chitchatter/actions/runs/6753125336). @dillfrescott please let me know if this is working for you!

**Comment by dillfrescott** [comment]
Awesome okay! If I don't report back assume it works haha!
