### ISSUE TITLE
OTP feature for room links

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#2]
Chitchatter needs an integrated [OTP](https://en.wikipedia.org/wiki/One-time_password) feature for securely sharing room links with peers. Something like https://burnernote.com/, but entirely client-side and built directly into Chitchatter.

### Sharer experience

- There is a new menu item called "Secure Invite"
- When the user (Sharer) clicks "Secure Invite," they are redirected to a new route called `/otp`
- The `/otp` route presents the user with a form that accepts a room name
- When Sharer submits the form, the form is replaced with:
  - A Chitchatter Secure Link that can be shared with someone (a Sharee)
    - The Secure Link should direct users to a new `/otp/:otpId` route (example: `https://chitchatter.im/otp/3b5ac1ff-e1c0-4797-9988-21a3e70302f2`)
  - A message informing Sharer that they must keep their tab open until Sharee has accessed the Secure Link
  - When Sharee successfully accepts the invite and accesses the chat room, Sharer is automatically redirected to the chat room as well

### Sharee experience
 
- When a user (Sharee) navigates to the `/otp/:otpId` Secure Link as provided by Sharer (see above), they are presented with a button to accept the invite
- When Sharee accepts the invite, they are redirected to the room that the Sharer specified

## Notes

This is just the first iteration of this feature. In the future, we should add the following enhancements:
  - Password-protected OTP links
  - Capability to share Secure Links with more than one person

![Secure Invite mockup](https://user-images.githubusercontent.com/366330/189538924-a3cefa24-4414-4036-85a8-6c132ccbd6fa.png)

**Comment by moh-mukarram** [comment]
can you assign me with this work?

**Comment by jeremyckahn** [comment]
Hi @moh-mukarram, thank you for offering to help with this! Before assigning this, I'd like to take some time to more clearly spec out how I'm thinking this might work. I'll follow up here once I have something a little more concretely defined, and we can go from there.

**Comment by jeremyckahn** [comment]
@moh-mukarram I've updated this ticket to include proper Acceptance Criteria. Please take a look and let me know what you think. If this seems like a reasonable design to you and something you'd like to own, please let me know and I will assign this issue to you!

**Comment by moh-mukarram** [comment]
hey  @jeremyckahn 
I have gone through given Acceptance Criteria.
Can you please explain what's the difference between OTP featured and Private room(issue#3).

**Comment by jeremyckahn** [comment]
Hi @moh-mukarram, OTP and Private Rooms (#3) have different use cases. OTP is for sharing a room name in a secure way, and Private Rooms are for allowing only people with the correct password to join the room. I'm envisioning these two features being used in conjunction for maximum security, but they could also be used separately.

I think that #3 is worth implementing first, in case you're interested in doing that work. I just added acceptance criteria to that ticket, so let me know if you'd prefer to do that instead!
