### ISSUE TITLE
Audio and trasfer of files not working

### ISSUE THREAD

**Issue by Tortar** [jeremyckahn/chitchatter#211]
Very cool project but when testing the application, I found that video streaming and text messages work, but audio and trasfer of files seem not to work instead. I'm not sure what kind of data do you need to diagnose the problem, but I'm willing to share some if asked for them

**Comment by jeremyckahn** [comment]
Hi @Tortar, thanks for reporting this. I've noticed that ad/content blockers can disrupt some data transfers. Could you see if disabling any browser content blockers improves the issue for you?

Also, could you please share what browser/device you're seeing this on?

**Comment by Tortar** [comment]
so sorry for the very late response, but I re-tested the app now and everything works great!!! It's an awesome project, thank you
