### ISSUE TITLE
Volume slider bugged with the addition of pgp key button

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#217]
![Screenshot_20231209_203126](https://github.com/jeremyckahn/chitchatter/assets/56714680/5cf074f9-a077-44fd-92c1-4e315a4add23)

It seems to have messed with the slider

**Comment by jeremyckahn** [comment]
Oh no! Thanks for reporting this @dillfrescott. I'm working on a fix right now. Sorry about that!

**Comment by dillfrescott** [comment]
No worries! Take your time!

**Comment by dillfrescott** [comment]
Thanks!

**Comment by jeremyckahn** [comment]
The fix (#218) is merged and [deployed](https://github.com/jeremyckahn/chitchatter/actions/runs/7154979379). Thanks again for reporting this @dillfrescott!
