### ISSUE TITLE
Add TURN Server with Port 80 and 443

### ISSUE THREAD

**Issue by dhuschde** [jeremyckahn/chitchatter#225]
Some networks block all ports except 443 and 80.

Chitchatter doesn't work in such networks.
Please add these Ports to your Server if possible.

**Comment by jeremyckahn** [comment]
Hi @dhuschde, thanks for raising this but I'd rather not make this change. Running the TURN server with ports normally allocated to other programs seems likely to cause confusion and stability issues. If you need Chitchatter to use a TURN server with those ports, I'd recommend [self-hosting](https://github.com/jeremyckahn/chitchatter#self-hosting) the app and making the necessary configuration changes for your instance.
