### ISSUE TITLE
Screenshare with audio needs it's own volume bar!

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#230]
Right now, when you screenshare with audio, it goes off of the person's main volume, which can be an issue especially if they are sharing their screen and have their microphone off, meaning the volume is un-adjustable.

It should be a separate volume bar on the right hand side, so it can avoid these issues.

**Comment by jeremyckahn** [comment]
Hi @dillfrescott! I think this is a good idea. I’m pretty busy for the next few weeks and need to wrap up some inflight work first, but I can get to this when I’m available (unless someone else wants to pick this up sooner). 🙂

**Comment by dillfrescott** [comment]
Ok that sounds good! No hurry!

**Comment by dillfrescott** [comment]
Thanks Jeremy!

**Comment by jeremyckahn** [comment]
You're welcome, @dillfrescott! Good idea to add this. Let me know how it works for you!
