### ISSUE TITLE
Relay server constantly unavailable

### ISSUE THREAD

**Issue by mahdibhaiya** [jeremyckahn/chitchatter#247]
Recently, everytime me and another peer join a room, the relay server is always unavailable, causing a partial server connection. Neither of us can see anyone in the server, most likely due to this.

**Comment by jeremyckahn** [comment]
Hi @mahdibhaiya, thanks for reporting this. The TURN server IP recently changed, but Chitchatter's configuration was fixed in #246. The fix has been deployed. Please let me know if you have any more issues!

**Comment by brentonv** [comment]
@jeremyckahn I think there are still issues with this. I haven't been able to connect in the last week

**Comment by jeremyckahn** [comment]
> I think there are still issues with this. I haven't been able to connect in the last week
> 
> Edit: Please disregard, I just noticed you re-opened #112

@brentonv, yes unfortunately this is going to be the case until someone from the community volunteers a TURN server for Chitchatter. I anticipate that we will have one available from our previous volunteer again in the future, but there's no timeline for that. I'm not in a position to host the TURN server myself, so hopefully somebody else is able to step forward to ensure reliable P2P Chitchatter connections.
