### ISSUE TITLE
License: MIT

### ISSUE THREAD

**Issue by SealedServant** [jeremyckahn/chitchatter#265]
I suggest that the project utilize the more permissive MIT license. 

Many of the project dependencies (i.e. trystero and vite) utilize the MIT license for developer freedom.

**Comment by jeremyckahn** [comment]
Thank you for the suggestion @SealedServant, but I'd rather stick with the GPL license for Chitchatter. Of all licenses I'm aware of, the GPL is most consistent with this project's goals of transparency and user freedom.
