### ISSUE TITLE
Build issues using Windows

### ISSUE THREAD

**Issue by brentonv** [jeremyckahn/chitchatter#267]
NodeJS and NPM are current

`package.json`
"build:app": "cross-env VITE_HOMEPAGE=$(npm pkg get homepage) vite build" fails
"build:sdk": "parcel build sdk/sdk.ts --no-content-hash" works

`npm run dev`
![npm-dev](https://github.com/jeremyckahn/chitchatter/assets/2313757/f646a193-ec08-4316-b270-59abe9ae0789)

`npm run test`
![npm-test](https://github.com/jeremyckahn/chitchatter/assets/2313757/599c7da0-5884-45d3-8217-4108406a534e)

`npm run build`
![npm-build](https://github.com/jeremyckahn/chitchatter/assets/2313757/b7455862-6982-4aff-a1dc-288f21979014)

**Comment by jeremyckahn** [comment]
Hi @brentonv, thanks for reporting this. I think this is happening because the `scripts` in `package.json` are written for *NIX systems like Linux and macOS. Are you able to use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) for development for this project? That should resolve the issues you're seeing.

**Comment by brentonv** [comment]
> I think this is happening because the `scripts` in `package.json` are written for *NIX systems like Linux and macOS

Yeah I get this with `npm install`:
npm ERR! Error: No native build was found for platform=win32 arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.12.1
npm ERR! attempted loading from: C:\Users\Brenton\Downloads\chitchatter-develop\node_modules\lmdb and package: @lmdb/lmdb-win32-x64

Thanks to everyone involved, this project is brilliant

**Comment by jeremyckahn** [comment]
> Yeah I get this with `npm install`:
> npm ERR! Error: No native build was found for platform=win32 arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.12.1
> npm ERR! attempted loading from: C:\Users\Brenton\Downloads\chitchatter-develop\node_modules\lmdb and package: @lmdb/lmdb-win32-x64

Thanks for sharing this! It's not surprising that various things aren't working properly in Windows, as I primarily develop on Linux systems.

I'll add a note in the README to use WSL when developing on Windows.

> Thanks to everyone involved, this project is brilliant

Thank you! 🙂
