### ISSUE TITLE
Private room password prompt

### ISSUE THREAD

**Issue by brentonv** [jeremyckahn/chitchatter#274]
Could you please show the private room password prompt before launching the room. Currently if it's clicked in error there is no way to escape the prompt without reloading the page.

It would be more user friendly if the prompt was dismissible, either by clicking a close icon in the top-right corner, clicking outside the dialog or pressing the escape key.

Thanks,

**Comment by jeremyckahn** [comment]
Hi @brentonv, thanks for raising this. I agree that the UX for private rooms is a little awkward. I think updating the password prompt dialog with a "go back" button that brings the user to the Home page might be all that's needed here. What do you think?

**Comment by brentonv** [comment]
Yeah I did some testing with closing the prompt and considered that as a simple option instead of requiring some rewrite. Personally I would prefer if the prompt was presented first, but up to you

**Comment by jeremyckahn** [comment]
> Personally I would prefer if the prompt was presented first

The idea with the current UX is that the password dialog appears in the shareable private room link. It would be possible to show the password dialog before the user is routed from the Home screen to the Private Room screen and also support the current UX, but that adds a bit more complexity. We could consider that in a future iteration, but for now it seems that the simplest solution is to add a "go to home screen" button to the current password dialog.

I'm pretty busy with other tasks at the moment, but I can add this when I have time. It shouldn't be a big lift to implement this, so others are welcome to submit a PR to add it before I get around to it.

**Comment by brentonv** [comment]
> the simplest solution is to add a "go to home screen" button

All that's needed is simple "x" in the top right corner, which will go back to the home screen when clicked

**Comment by jeremyckahn** [comment]
> All that's needed is simple "x" in the top right corner, which will go back to the home screen when clicked

This seems like a confusing UX to me. Generally speaking, I don't think that dismissing a modal should cause a navigation. A button that explicitly states what will happen if pressed seems more straightforward.

**Comment by Con198811** [comment]
Hello Jeremy I ended up in this site through messing around with Pythonista web scraping 😂

**Comment by brentonv** [comment]
> I ended up in this site through messing around with Pythonista web scraping 😂

I used Google🤣

**Comment by brentonv** [comment]
@jeremyckahn I just realized that any changes made will affect how the embedded code works, so it's probably best to just leave it how it is..?

**Comment by jeremyckahn** [comment]
> I just realized that any changes made will affect how the embedded code works

I hadn't thought of that! I was just focusing on the UX. But I think you're right here; it's probably best to stick with a "go to home screen" button. I think the new button should only show when Chitchatter isn't running in "embedded" mode, as the embedded experience should never take the user to the Home screen.

**Comment by brentonv** [comment]
@jeremyckahn thanks mate👍
