### ISSUE TITLE
Unknown error...

### ISSUE THREAD

**Issue by Zibri** [jeremyckahn/chitchatter#286]
What I did:

1) I forked the repository.

2) I modiefied the Deploy to github pages so that the GITHUB_TOKEN can use the api.

3) used the most recent github api to deploy to pages.

4) removed the CNAME.

result:
https://zibri.github.io/chitchatter/index.html

The strange thing is that if I load the manifest or the script files manually, they work.

Any ideas?

P.S.
if you are available I'd like to chat with you because I have a few ideas... I wrote a very similar application some time ago, using a different and better method (instead of torrent announcements)
Tell me if you are available...

**Comment by Zibri** [comment]
P.S.
I had the same error when I used your workflow... and I had to add the permissions for the github token anyway.

**Comment by Zibri** [comment]
hmm I understood... the reason is that my github page is a subpage.. and it searches for the manifest in the webroot zibri.github.io...

**Comment by jeremyckahn** [comment]
Hi @Zibri, can you try uncommenting this line in your fork? https://github.com/jeremyckahn/chitchatter/blob/65c4c4890ad6be76d68e222619b320da6355cae6/vite.config.ts#L38

Here's a fork that seems to be working: https://github.com/jeremyckahn/chitchatter/compare/main...AtaraxiaSjel:chitchatter:main#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR38

Can you try adapting your config to be similar to this?

**Comment by Zibri** [comment]
yep! thanks! it works.

**Comment by jeremyckahn** [comment]
You're welcome @Zibri. I've updated [the self-hosting instructions](https://github.com/jeremyckahn/chitchatter?tab=readme-ov-file#self-hosting) to hopefully make this a bit more straightforward.
