### ISSUE TITLE
StreamSaver.js not working

### ISSUE THREAD

**Issue by brentonv** [jeremyckahn/chitchatter#288]
If I try to save anything using "..files being offered by.." it gives a [GitHub 404 error](https://jeremyckahn.github.io/StreamSaver.js/chitchatter.im/081119/1677583850c7278f159032f6f34b15f91104da12bb_thumbnail_720x.jpg).
I'm not sure how to troubleshoot this, but it appears to be broken

**Comment by brentonv** [comment]
Update: It's working after disabling download manager.
Not sure how that would cause it to fail?

**Comment by jeremyckahn** [comment]
Thanks for the report and update, @brentonv. Can you provide some more information about what you mean about disabling your download manager? Is that something built into the browser you're using?

**Comment by brentonv** [comment]
Hi @jeremyckahn, my browser is set to catch all downloads using[ FDM](https://www.freedownloadmanager.org) and I'm assuming it doesn't process the StreamSaver.js as it would normally using the browser. Sorry for raising this as an issue

**Comment by jeremyckahn** [comment]
Thanks for the additional information, @brentonv. It appears that this is a known issue with StreamSaver.js: https://github.com/jimmywarting/StreamSaver.js/issues/325

I can add a note to the README to cover this.
