### ISSUE TITLE
[feature] please add the possibility to retrieve iceservers from a remote host.

### ISSUE THREAD

**Issue by Zibri** [jeremyckahn/chitchatter#290]
I tried to modify the code for that but I did not succeed.
In normal javascript is quite simple:

        const response = await fetch('https://my.server.org', options|{});
        const iceServers = await response.json();

**Comment by jeremyckahn** [comment]
Hi @Zibri, it's not clear to me what you're trying to achieve here. What is your end goal?

**Comment by Zibri** [comment]
I wish we could chat so I will explain it to you.

**Comment by jeremyckahn** [comment]
I don't know that what's being asked here is feasible, so I'm going to close this issue for now. @Zibri feel free to continue the discussion here if you'd like to discuss your end goal further.
