### ISSUE TITLE
Sending large image breaks site layout

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#308]
![Screenshot 2024-06-04 215903](https://github.com/jeremyckahn/chitchatter/assets/56714680/a6c99a2a-5882-47c1-b09c-2a9c7cd2376b)

**Comment by dillfrescott** [comment]
Hmm actually it seems to be just about any image

**Comment by jeremyckahn** [comment]
Thanks for reporting this, @dillfrescott. This is related to #280.

I might be able to address this soonish, but others can pick up and address this issue as well.

**Comment by dillfrescott** [comment]
Oh, okay!

**Comment by jeremyckahn** [comment]
This is fixed in https://github.com/jeremyckahn/chitchatter/commit/a8dff459f332c0b8240d6d61d43e268be3edfd8a and is [deploying now](https://github.com/jeremyckahn/chitchatter/actions/runs/9384749487/job/25841238300). Thanks again for reporting @dillfrescott!

**Comment by dillfrescott** [comment]
no problem!
