### ISSUE TITLE
Bug: I'm having issues with videos rendering in chat

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#311]
Images work fine, but videos tend to either spin forever or the play is grayed out and either way the thumbnail or video doesnt show up, just the box with the play pause and stuff.

**Comment by jeremyckahn** [comment]
Thanks for reporting this @dillfrescott. I am able to reproduce with a relatively small Big Buck Bunny test video: https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4.

This seems to be an issue somewhere upstream in the libraries that Chitchatter is using to implement video embeds (https://github.com/webtorrent/webtorrent/issues/1887). I don't have time to properly diagnose and fix this issue, so I'm going to look to disable it for now.

**Comment by dillfrescott** [comment]
Gotcha! Okay

**Comment by jeremyckahn** [comment]
This is addressed in https://github.com/jeremyckahn/chitchatter/commit/56dbbf2665424920fe46eb528b82ed50c7f7c77b. With this change, inline media rendering will abort and print an error message if the file extension is unsupported. This is a quick fix and it's not as graceful as I'd like, but it should at least avoid users dealing with an obviously-broken experience.

Thanks for reporting this @dillfrescott!

**Comment by brentonv** [comment]
Wow [videostream](https://github.com/jhiesey/videostream) "only mp4 files are supported" and "mp4 files with certain audio codecs not playing" and last commit "Nov 12, 2020"

**Comment by dillfrescott** [comment]
Oh damn. Yeah looks like a better solution is in order.

**Comment by jeremyckahn** [comment]
Yeah... some of the libraries that Chitchatter depends on are a little old and creaky. They generally work well enough, but there are some rough edges like this. I don't know of any modern, maintained alternatives. :confused:
