### ISSUE TITLE
Image sharing

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#33]
Users should be able to upload image files to each other.

**Comment by ighmaZ** [comment]
Hi @jeremyckahn , i would love to work on this

**Comment by jeremyckahn** [comment]
Go for it @ighmaZ! I will assign this to you. However, please note that I won't really be able to help with the design or implementation of this feature. I haven't worked out how it should work yet, and I'm pretty busy with a few other things these days. If you're okay with that, this ticket is yours.

Thanks for offering to help out with this! 🙂

**Comment by ighmaZ** [comment]
@jeremyckahn i'll give my best Jeremy :)

**Comment by jeremyckahn** [comment]
@ighmaZ do you mind if I take this back? I've got an idea in mind for implementing this that I'd like to try.

**Comment by ighmaZ** [comment]
Sure Jeremy! I started working as a developer, i dont get enough time😭

**Comment by jeremyckahn** [comment]
No worries. I'll take this back for now. Congrats and good luck with the new job @ighmaZ!

**Comment by ighmaZ** [comment]
Thanks jeremy! Would definitely love to contribute more in the future☺️

**Comment by jeremyckahn** [comment]
That would be great! Just let me know when you're ready. 🙂

**Comment by ighmaZ** [comment]
Sure mate
