### ISSUE TITLE
Having problem on firefox browser

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [jeremyckahn/chitchatter#36]
### Discussed in https://github.com/jeremyckahn/chitchatter/discussions/35

<div type='discussions-op-text'>

<sup>Originally posted by **MohammadTaseenKhan** October  9, 2022</sup>
> Recently I am facing a new problems like when i use Firefox browser i cant send any message, even cant receive any message even no notification coming to me

Sending Message:
![image](https://user-images.githubusercontent.com/85288261/194734929-db736a32-3483-46bf-b63a-c31c1dfcdf00.png)

Receiving message:
![image](https://user-images.githubusercontent.com/85288261/194734944-537abcdc-dbdd-4178-99bc-eadfceaf0840.png)

It doesn't even showing how many numbers of peers are connected

![image](https://user-images.githubusercontent.com/85288261/194734976-622ca92c-ac27-4ad0-8fb8-5c1684d5fff1.png)

same as well this also

![image](https://user-images.githubusercontent.com/85288261/194734993-259ef90a-eba0-47b9-afea-914f940820b9.png)

https://chitchatter.im/public/85ccdfc7-b992-411d-9d98-0a5c2781138e</div>

**Comment by MohammadTaseenKhan** [comment]
But when I use Chrome or Brave It works fine

**Comment by jeremyckahn** [comment]
Hi @MohammadTaseenKhan, thank you for the detailed bug report! I'm not able to reproduce this in any browser. I noticed you are using Firefox ESR. I downloaded the latest Firefox ESR for Linux and was unable to reproduce there as well. This seems like an issue that may be specific to your environment. I have a few questions:

  - Are you seeing anything concerning in the browser console?
  - Are you sure that WebRTC is enabled in your Firefox ESR?
  - Do you have any other non-default settings that might affect WebRTC/peer connections?

Hopefully these questions will help to narrow down the cause of this issue!

**Comment by MohammadTaseenKhan** [comment]
@jeremyckahn The problem has been fixed

I just needed to enable the **media.peerconnection.enabled** In **about:config** section

**Comment by jeremyckahn** [comment]
Nice work getting to the bottom of this, @MohammadTaseenKhan! I've updated the README to help others who may run into this: https://github.com/jeremyckahn/chitchatter#firefox-specific
