### ISSUE TITLE
Bandwidth spam settings

### ISSUE THREAD

**Issue by Agility0493** [jeremyckahn/chitchatter#380]
Is there a setting to change how much bandwidth users can have to prevent them spamming large files and wasting TURN server resources?

**Comment by jeremyckahn** [comment]
There isn't, and I don't know that this sort of functionality would be helpful. It seems that [TURN servers are only used when necessary](https://chatgpt.com/share/6741f637-8d04-8011-99eb-2c4367edd9fa), so selectively disabling them would cause Chitchatter to not work at all.
