### ISSUE TITLE
Empty room id in URL displays empty page  

### ISSUE THREAD

**Issue by krayste** [jeremyckahn/chitchatter#59]
If you remove the room ID, such as `https://chitchatter.im/private/`, or `https://chitchatter.im/public/`, the page displays nothing
![image](https://user-images.githubusercontent.com/18077772/198832541-31cdee50-112a-4ece-add4-10e422942c5c.png)
![image](https://user-images.githubusercontent.com/18077772/198832546-bb22188e-94ed-4c97-8eaf-5443314687ea.png)

**Comment by jeremyckahn** [comment]
Thanks for reporting this @krayste! I'm deploying the fix for this now.
