### ISSUE TITLE
Show notifications for new messages

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#6]
When a user receives a message and the Chitchatter room is not in focus, present an [operating system-level notification](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) to inform the user that there is a new message. This functionality should be off by default, but able to be enabled via a persisted user setting.

**Comment by jeremyckahn** [comment]
@ighmaZ Let me know if you'd like to work on this. Regarding this part:

> This functionality should be off by default, but able to be enabled via a persisted user setting.

These is no user settings UI yet, so that work could be deferred to a later ticket that I can write up. If we do that, then notifications should be **on** by default.

**Comment by ighmaZ** [comment]
@jeremyckahn , ill take this issue! ill do my best

**Comment by jeremyckahn** [comment]
@ighmaZ Good luck! Let me know if I can help. 🙂

**Comment by ighmaZ** [comment]
hi @jeremyckahn ! how do i start working on it? any help?

**Comment by jeremyckahn** [comment]
@ighmaZ Were you able to get the app running locally? You should just need to clone the Git repo, run `npm run ci` and then `npm run dev`. Let me know if you need more information!

**Comment by ighmaZ** [comment]
hi @jeremyckahn ! i have got this app running locally! but not sure how do i start working on it, i am actually new to open source

**Comment by jeremyckahn** [comment]
@ighmaZ Awesome! How familiar are you with React development? If you have no prior experience, I'd recommend getting up to speed at https://reactjs.org/tutorial/tutorial.html. Chitchatter is built with the [Create React App](https://create-react-app.dev/) tool chain, so refer to that project's documentation to get a sense of the overall project setup.

To implement this feature, we'll want to [display a notification](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) when a peer receives a message. Message receipt is handled here: https://github.com/jeremyckahn/chitchatter/blob/2fabd4d974e1b382a082c7d706a1f59986f18e92/src/components/Room/Room.tsx#L98-L100

We will also need to [request permission from the user to display notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission). I haven't looked into this much yet, but it seems sensible to request permission when a user joins a room. To achieve this, we could have a [`useEffect`](https://reactjs.org/docs/hooks-effect.html) hook perform this when the `Room` component is mounted. That can be achieved by putting something like this inside of the component in [`src/components/Room/Room.tsx`](https://github.com/jeremyckahn/chitchatter/blob/develop/src/components/Room/Room.tsx):

```tsx
useEffect(() => {
  // Request permission to display notifications here
  // https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission#examples
}, [])
```

Hopefully this is helpful. Let me know if you need further guidance!

**Comment by ighmaZ** [comment]
@jeremyckahn ! i am  good with react,it was helpful, u explained so well captain! i'll work on this

**Comment by ighmaZ** [comment]
sorry @jeremyckahn ! i think its a lil difficult task for me. i having having a hard time solving it

**Comment by jeremyckahn** [comment]
No worries @ighmaZ. What have you tried so far?

Let me know if you would like to keep trying with this, or if you would prefer that the ticket be unassigned from you.

(FYI, I won't be very available this week, so my responses may be delayed until the weekend.)

**Comment by ighmaZ** [comment]
hi @jeremyckahn !
this is what i have tried so far.

 useEffect(() =>{

   function showNotification(){

    const notification = new Notification("You have a new message")
    
   }


  if(Notification.permission === "granted"){   // to ask for permission

   showNotification();
  }
  else if (Notification.permission !== "denied"){
  
    Notification.requestPermission().then((permission) =>{

      if (permission === "granted") {

        showNotification();
        // …
      }
    })
  }

 },[])

**Comment by jeremyckahn** [comment]
@ighmaZ this seems like a reasonable start. What do you think about opening up a Draft PR so that I can pull down your changes and try to debug it?

**Comment by ighmaZ** [comment]
@jeremyckahn ! thanks Jeremy! ill do it

**Comment by jeremyckahn** [comment]
This ticket is now free for anyone who wants to work on it.
