### ISSUE TITLE
Play a sound for new messages

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#7]
When a user receives a message and the Chitchatter room is not in focus, play a sound to inform the user that there is a new message. This functionality should be off by default, but able to be enabled via a persisted user setting.

**Comment by Flaykz** [comment]
Hi, can you authorize me to do a pull request for this ? Thx :)

**Comment by jeremyckahn** [comment]
Hi @Flaykz, thanks for your interest in Chitchatter! Opening a PR requires no authorization, so feel free to open one whenever you’d like.

**Comment by Flaykz** [comment]
nice done :)
