### ISSUE TITLE
Is there a way to set my username?

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#76]

**Comment by jeremyckahn** [comment]
Hi @dillfrescott, right now this functionality is not supported. I consider the lack of name customization a security feature, as it should help to prevent users from impersonating others. This might be revisited if Chitchatter ever supports a way to host "personal" rooms (where one peer has administrative rights that other peers don't), but for now I'd like to keep this functionality out of the project.

**Comment by dillfrescott** [comment]
Gotcha. I understand

**Comment by dillfrescott** [comment]
Wait I did think of something. Maybe just a "display name" that can be set, but a randomized handle you cant change, that way even if someone sets their name as someone else, you can still tell its a different person by the handle.

**Comment by jeremyckahn** [comment]
I think that would make sense. We could have an "alias" that users can customize, but the static friendly animal name could still show alongside it. Perhaps something like this:

![User alias mockup](https://user-images.githubusercontent.com/366330/205502822-2317d7b5-2dcb-432d-897e-f8387fddfd4d.png)

I think that would be a good addition. I'll reopen this ticket!

**Comment by jeremyckahn** [comment]
@dillfrescott I won't have availability to work on this until next month at the earliest, so let me know if you'd like to pick this up.

**Comment by dillfrescott** [comment]
Oh awesome! I'm glad you like the idea! Im in no hurry so you can add it whenever you feel like it!

**Comment by karlerik-simon** [comment]
I can have my go at it, see if I'm able to do much

**Comment by jeremyckahn** [comment]
@karlerik-simon thanks for offering to pick this up! Feel free to open a PR and I'll help you get it merged. I'll assign this issue to you. Let me know if you need any help!

**Comment by karlerik-simon** [comment]
Perfect! No problem, thanks for assigning the issue to me

**Comment by jeremyckahn** [comment]
@karlerik-simon have you made much progress with this feature? If not, would you mind if I reassigned this issue to myself? It looks like @dillfrescott would really like to see this implemented and I've got some bandwidth to work on it now.

**Comment by dillfrescott** [comment]
Please dont make me rush you guys. Id just love to see it as a feature is all!

**Comment by dillfrescott** [comment]
@jeremyckahn I was testing the name change branch and it works great! I do think there should be a setting to remember your chosen nickname across rooms though. Just so one doesn't have to type it in for every room they join if they so desire!

**Comment by jeremyckahn** [comment]
@dillfrescott good idea! I agree. 🙂 FWIW, the name change work is still in development and there are still some kinks to work out. It should at least be stable, if incomplete. Please let me know if you run into any crashes or instability in your testing!

**Comment by dillfrescott** [comment]
@jeremyckahn Will do! Thank you!

**Comment by jeremyckahn** [comment]
@dillfrescott This is done and deploying now: https://github.com/jeremyckahn/chitchatter/actions/runs/4332396581

Let me know how you like it!
