### ISSUE TITLE
Ability to adjust volume of other users

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#77]
Please!!!

**Comment by jeremyckahn** [comment]
Hi @dillfrescott, I think this is a great idea. I think some reworking of audio/video streams will need to happen before this can be done. Right now audio and video streams are handled independently, which is probably not optimal in terms of performance. Once the streams are combined, audio/video signals can be output via `<video />` elements that can expose volume controls.

**Comment by dillfrescott** [comment]
Okay!

**Comment by dillfrescott** [comment]
Sorry to bother, but are we any closer to having a volume adjustment? :)

**Comment by jeremyckahn** [comment]
Hi @dillfrescott, I haven’t had a chance to work on this yet. My spare time is divided across a few projects, so I need to prioritize helping PRs from others along and bug fixes over implementing new features myself. If you’d like to open a PR to implement this feature, I’ll be able to help you expedite it from there.

**Comment by dillfrescott** [comment]
Oh wonderful!

**Comment by jeremyckahn** [comment]
@dillfrescott this feature has been implemented by #90. Please let me know how it works for you! 🙂

**Comment by dillfrescott** [comment]
@jeremyckahn Works great! You implemented it better than I could have imagined! Thank you so much!

**Comment by dillfrescott** [comment]
I love this software!
