### ISSUE TITLE
Nextjs implementation

### ISSUE THREAD

**Issue by yorktlo** [jeremyckahn/chitchatter#89]
Great work so far!

I'm trying to migrate this from CRA to nextjs, any clue if this is possible at all? Currently it's showing "_Error: Trystero: already joined room_".

**Comment by jeremyckahn** [comment]
Thanks, I'm glad you're liking Chitchatter so far! 🙂

> Currently it's showing "_Error: Trystero: already joined room_".

I've noticed this happen when the `Room` component is re-mounted (which only occurs in development in my experience). Can you check to see if this is happening, and prevent it if so?

**Comment by yorktlo** [comment]
Ah fixed it! I was previously troubleshooting another issue so I turned off occupiedRoom[ns]. Although now I'm getting a different error "_TypeError: f is not a function_"...

**Comment by jeremyckahn** [comment]
> Although now I'm getting a different error "_TypeError: f is not a function_"...

I'm not sure what might be causing that. It sounds like it might be something specific to your environment, perhaps? It's hard to say without seeing the code that's causing the issue and/or screenshots.

I'm going to close this for now, as this thread doesn't appear to be about an issue or feature request for Chitchatter. For more general Q&A like this, please open [a discussion thread](https://github.com/jeremyckahn/chitchatter/discussions).
