### ISSUE TITLE
Request: Include commit hash on main page so you know what version you are using

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#94]
I think this would be really cool!

**Comment by dillfrescott** [comment]
Not sure if its possible though...

**Comment by jeremyckahn** [comment]
Good idea @dillfrescott! I think this should be achievable through [Create React App environment variables](https://create-react-app.dev/docs/adding-custom-environment-variables/).

**Comment by dillfrescott** [comment]
@jeremyckahn I am hosting a self hosted version that I deploy via vercel, and when I click on the hash on the main page it links to an unknown has under your main repo...

**Comment by dillfrescott** [comment]
https://chat.dill.moe/ here is the link to my deployment so you can test the issue yourself

**Comment by jeremyckahn** [comment]
> @jeremyckahn I am hosting a self hosted version that I deploy via vercel, and when I click on the hash on the main page it links to an unknown hash under your main repo...

I think you'll need to tweak [this line](https://github.com/jeremyckahn/chitchatter/blob/37af59f89ed3fbf57bc0cfae625fc0de701fbed8/.env#L2) to point to your source repo to make the link work correctly.

**Comment by dillfrescott** [comment]
Oh! Okay thank you.

**Comment by dillfrescott** [comment]
Works great! Thanks again!
